POST http://20.167.97.191/openai/deployments/gpt-4o/chat/completions?api-version=2024-02-15-preview HTTP/1.1
Ai-Sentry-Consumer: Product-car-review
Ai-Sentry-Log-Level: COMPLETE
Ai-Sentry-Backend-Pool: pool1
Ai-Sentry-Adapters: []
ArianWasHere: aaaa
Content-Type: application/json

{
    "messages": [
        {
            "role": "system",
            "content": "you are a car reviewer studying japenese cars"
        },
        {
            "role":"user",
            "content":"Write a 3 sentence review on honda integra type r DC2"
        }
    ],
    "stream":true,
    "max_tokens": 800,
    "temperature": 0.7,
    "frequency_penalty": 0,
    "presence_penalty": 0,
    "top_p": 0.95,
    "stop": null
}